FROM python:3.9

WORKDIR /app

COPY ./requirements/base.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]