from enum import Enum

class BankBrand(Enum):
    BBVA = "BBVA"
    SANTANDER = "SANTANDER"
    BANORTE = "BANORTE"
    HSBC = "HSBC"
    CITIBANAMEX = "CITIBANAMEX"
    SCOTIABANK = "SCOTIABANK"
    INBURSA = "INBURSA"
    MULTIVA = "MULTIVA"
    BANREGIO = "BANREGIO"
    AZTECA = "AZTECA"
    AMERICAN_EXPRESS = "AMERICAN_EXPRESS"
    UNKNOWN = "UNKNOWN"
    