"""initial migration

Revision ID: 5e085dc05752
Revises: 
Create Date: 2025-11-09 00:36:11.712441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e085dc05752'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('bank_type', sa.Enum('BBVA', 'SANTANDER', 'BANORTE', 'HSBC', 'CITIBANAMEX', 'SCOTIABANK', 'INBURSA', 'MULTIVA', 'BANREGIO', 'AZTECA', 'AMERICAN_EXPRESS', 'UNKNOWN', name='bankbrand'), nullable=False),
    sa.Column('bank_code', sa.String(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('INGESTED', 'CLASSIFIED', 'TEXT_EXTRACTED', 'PARSED', 'NORMALIZED', 'VALIDATED', 'DONE', 'FAILED', name='docstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='typetransaction'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_document_id'), 'transactions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_document_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('documents')
    # ### end Alembic commands ###
